**[Python Basics](#1)**
1. [List, Tuple, Dictionary](#2)
2. [For Loop,  lambda and anonymous function, zip,  list compreherension](#3)
3. [Numpy Array, Pandas Series](#4)
    

**[Working with Dataframes](#5)**
1.  [Pandas Dataframes](#6)
2.  [Read Data(info, columns, head...)](#7)
3.  [Regulating Data (NaN values, String values to Numeric)](#8)
4.  [Indexing & Slicing (Reach and change index names, values; getting column names and values..)](#9)
5.  [Filtering and Transforming (Lambda, Defining column, Creating boolen series, filters )](#10)
6.  [Data Analysis (describe: max, min, Q, IQR, std...)](#11)
7.  [Concatenating](#12)
8.  [Pivoting (Reshaping dataframes)](#13)
9.  [Melting (Reshaping dataframes)](#14)
10. [Stacking and Unstacking (Reshaping dataframes)](#15)
11. [Groupby (basic functions: sum(), min(), max(), mean())](#16)
11. [Merging](#17)
     

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

<a id="1"></a>
# PYTHON BASICS

<a id="2"></a>
**1.1. LIST**

In [2]:
#Create list
num = [1,2,3,4,5,6]
num

[1, 2, 3, 4, 5, 6]

In [3]:
#Let's see its attribute
print(dir(num))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [4]:
#Add new element
num.append("foo") 
num

[1, 2, 3, 4, 5, 6, 'foo']

In [5]:
#Remove element
num.remove('foo') 
num

[1, 2, 3, 4, 5, 6]

In [7]:
print("All elements : ", num)
print("First 3 elements : ", num[:3])
print("Except first 3 elements  : ", num[3:])
print("4 to 6 elements: ", num[3:6])
print("5 to 2 elements: ", num[1:-2])

All elements :  [1, 2, 3, 4, 5, 6]
First 3 elements :  [1, 2, 3]
Except first 3 elements  :  [4, 5, 6]
4 to 6 elements:  [4, 5, 6]
5 to 2 elements:  [2, 3, 4]


**1.2. TUPLE**

Tuple has less attributes than compared to list.

In [8]:
#Creating Tuple
t1 = (6,"str",15,12,"foo",6)
t1

(6, 'str', 15, 12, 'foo', 6)

In [9]:
print("count(6)", t1.count(6)) # How many '6' does tuple have?
print("index('foo')", t1.index('foo')) # What's index of 'foo'

count(6) 2
index('foo') 4


**1.3. DICTIONARY**

In [19]:
dic = {"alice" : 23, "bob" : 12, "steve": 45}
dic

{'alice': 23, 'bob': 12, 'steve': 45}

In [20]:
#Get Steve value
dic["steve"]

45

In [21]:
#Get bob value
dic.get("bob")

12

In [22]:
print(dic.keys())
print(dic.values())
dic.pop("steve") # remove steve

dict_keys(['alice', 'bob', 'steve'])
dict_values([23, 12, 45])


45

In [23]:
#Another way to create a dic
x = dict([("Mad Men", "Drama"), ("The Office", "Comedy")])
x

{'Mad Men': 'Drama', 'The Office': 'Comedy'}

<a id="3"></a>
**2.1. FOR LOOP**

In [24]:
#Create list 
names = ["alice","bob","eva", "steve","jane", "billy"]

#print each element of list
for name in names:
    print(name)

alice
bob
eva
steve
jane
billy


In [25]:
#print each element of string
for i in 'alice':
    print(i)

a
l
i
c
e


In [29]:
#split() function is  return a list of word strings. 
for i in "alice and bob".split():
    print(i)

alice
and
bob


**2.2. LAMBDA AND ANONYMOUS FUNTION**

Like writing a function in a short way.

In [32]:
#Lambda Function
cube = lambda x: x**3
cube(3)

27

In [33]:
#Anonymous function is likely to lambda but it takes more arguments.
numbers = [2,3,4,5,6,7,8]
results = list(map(cube, numbers))
results

[8, 27, 64, 125, 216, 343, 512]

**2.3. ZIP**

It's like mapping two list. Lıst of tuples.

In [35]:
num1 = [1,2,3,4,5,6,7]
num2 = [5,'foo',8, 1.0, 'trathaka', 7]
z = zip(num1,num2)
print(z)
print(list(z))
type(z)

[(1, 5), (2, 'foo'), (3, 8), (4, 1.0), (5, 'trathaka'), (6, 7)]


zip

**2.4. LIST COMPREHENSION**

In [39]:
#Create a dictionary
dic1= { "Name":["alice","bob","clarke", "steve","eva", "jason"],
        "Ages":[15,16,20,23,13,18],
        "Salary":[100,232, 300, 50, 140,500] }
import pandas as pd
d = pd.DataFrame(dic1)
d

Name  Ages  Salary
0   alice    15     100
1     bob    16     232
2  clarke    20     300
3   steve    23      50
4     eva    13     140
5   jason    18     500

In [40]:
for i in dic1['Ages']:
    dic1["Ages"] = i + 1
    print(i)

15
16
20
23
13
18


In [43]:
#Creating new column, if salary > avarage write 'high' else 'low'
avg = sum(dic1["Salary"]) / len(dic1["Salary"]) #Avarage
dic1["new_column"] = ["high" if salary > avg else "low" for salary in dic1["Salary"]]
dic1

{'Name': ['alice', 'bob', 'clarke', 'steve', 'eva', 'jason'],
 'Ages': 19,
 'Salary': [100, 232, 300, 50, 140, 500],
 'new_column': ['low', 'high', 'high', 'low', 'low', 'high']}

In [44]:
#Creating new column, if salary > avarage write 'high' else 'low'
avg = sum(d["Salary"]) / len(d["Salary"]) #Avarage
d["new_column"] = ["high" if salary > avg else "low" for salary in d["Salary"]]
d

Name  Ages  Salary new_column
0   alice    15     100        low
1     bob    16     232       high
2  clarke    20     300       high
3   steve    23      50        low
4     eva    13     140        low
5   jason    18     500       high

In [45]:
d.drop('new_column', 1)

Name  Ages  Salary
0   alice    15     100
1     bob    16     232
2  clarke    20     300
3   steve    23      50
4     eva    13     140
5   jason    18     500

In [46]:
#Change column name
dic1["Status"] = dic1.pop("new_column")
dic1


{'Name': ['alice', 'bob', 'clarke', 'steve', 'eva', 'jason'],
 'Ages': 19,
 'Salary': [100, 232, 300, 50, 140, 500],
 'Status': ['low', 'high', 'high', 'low', 'low', 'high']}

In [48]:
d

Name  Ages  Salary new_column
0   alice    15     100        low
1     bob    16     232       high
2  clarke    20     300       high
3   steve    23      50        low
4     eva    13     140        low
5   jason    18     500       high

<a id="4"></a>
**3.1. NUMPY ARRAY** 

In [49]:
a = np.array([1,2,3,4,5,6,7,8,])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
a = a.reshape(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
print("shape : ", a.shape)
print("dimension : ", a.ndim)
print("data type : ", a.dtype.name)
print("size : ", a.size)
print("type", type(a))

shape :  (2, 4)
dimension :  2
data type :  int32
size :  8
type <class 'numpy.ndarray'>


In [52]:
#Create 3x4 matris and fill it with zeros
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
#Create a array: range of elements 5 to 20, increase 2
c = np.arange(5,20,2).reshape(4,2)
c

array([[ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [56]:
#Create a array, put into the 20 numbers to between 1 and` 10.
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [60]:
#To sum arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [61]:
a**2

array([1, 4, 9], dtype=int32)

In [62]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [63]:
c > 12

array([[False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [64]:
c[c>12]

array([13, 15, 17, 19])

In [65]:
#Element wise
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [66]:
#Dot product
a.dot(b.T) #b.T = b's tranpose

array([[14, 32],
       [32, 77]])

In [67]:
#Create random matrix 2x3
np.random.randint(2, 10,(2,3))

array([[3, 2, 5],
       [8, 5, 5]])

In [68]:
print("a : \n", a)
print("Sum of a:", a.sum())
print("Max of a: ", a.max())
print("Min of a: ", a.min())

a : 
 [[1 2 3]
 [4 5 6]]
Sum of a: 21
Max of a:  6
Min of a:  1


In [69]:
print("Sum rows : ", a.sum(axis=1))
print("Sum columns : ", a.sum(axis=0))

Sum rows :  [ 6 15]
Sum columns :  [5 7 9]


In [70]:
#Indexing and Slicing
a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(a)
print("\n",a[0:2,1:4])
print("\n", a[-1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 [[2 3 4]
 [7 8 9]]

 [[11 12 13 14 15]]


In [72]:
#SHAPE MANIPULATION
b = a.ravel()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
b = b.reshape(5,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [74]:
#ARRAY CONCAT
array1 = np.array([ [1,2], [3,4] ])
array2 = np.array([ [4,5], [6,7] ])
#VERTICAL
np.vstack((array1, array2))

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [76]:
#HORIZONTAL
np.hstack((array1, array2))

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])

In [77]:
#Convert
l = [1,2,3,4]
a = np.array(l)
a

array([1, 2, 3, 4])

In [78]:
list(a)

[1, 2, 3, 4]

In [79]:
tuple(a)

(1, 2, 3, 4)

In [80]:
#Copy
a = np.array(a)
b = a #Same address a and b
b

array([1, 2, 3, 4])

In [81]:
a[0] = 5
b

array([5, 2, 3, 4])

In [82]:
c = a.copy() # New address for c
c

array([5, 2, 3, 4])

In [83]:
a[0] = 1
c

array([5, 2, 3, 4])

**3.2. PANDAS SERIES**

    Understanding of series is important because it will be needed while working with dataframes. 
    Series is similar to one-dimensional labeled array.  
    It consist of indexes and their corresponding values.

In [84]:
#Creating a series
my_series = pd.Series([1,3,'string', 'f', 7.1, 10])
my_series

0         1
1         3
2    string
3         f
4       7.1
5        10
dtype: object

In [85]:
#Reaching values, index and rows
print("First 3 values : ", my_series[0:2].values)
print("Last 2 rows :")
my_series[-2:]

First 3 values :  [1 3]
Last 2 rows :


4    7.1
5     10
dtype: object

In [86]:
#Changing index names.
indexes = [3, "foo", 5, "float", 1, 10]
my_series.index = indexes
my_series

3             1
foo           3
5        string
float         f
1           7.1
10           10
dtype: object

In [87]:
#Getting the value with index name.
my_series["foo"]

3

In [88]:
#A dictionary can be put into  to series.
dictionary = {"Alice":25, "Bob" : 15, "Clarke": 19}
new_series= pd.Series(dictionary)
new_series

Alice     25
Bob       15
Clarke    19
dtype: int64

In [89]:
#Comprehension : new_series > 18 is return true or false
new_series[new_series>18]

Alice     25
Clarke    19
dtype: int64

In [90]:
#One another way to create series.
indexes = ["str", "float", "int"]
new_series = pd.Series([20,30,40], index=indexes)
new_series

str      20
float    30
int      40
dtype: int64

<a id="5"></a>
# WORKING WITH DATAFRAMES

<a id="6"></a>
**1.PANDAS DATAFRAMES**

In [91]:
dic1= { "Name":["alice","bob","clarke", "steve","eva", "jason"],
        "Ages":[15,16,20,23,13,18],
        "Salary":[100,232, 300, 50, 140,500] }
#Creating a dataframe
dt= pd.DataFrame(dic1)
dt

Name  Ages  Salary
0   alice    15     100
1     bob    16     232
2  clarke    20     300
3   steve    23      50
4     eva    13     140
5   jason    18     500

In [92]:
for i in dt.index:
    print(i)

0
1
2
3
4
5


In [95]:
for i in (dt.Name, dt.Ages):
    print(i)

0     alice
1       bob
2    clarke
3     steve
4       eva
5     jason
Name: Name, dtype: object
0    15
1    16
2    20
3    23
4    13
5    18
Name: Ages, dtype: int64


<a id="7"></a>
**2.READ DATA**

In [96]:
#Read Data from csv file
data = pd.read_csv(r"E:\Python\Machine Learning Projects\Python Basics, Numpy, Pandas for Data Science/Iris.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB


In [97]:
#Show columns names
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [102]:
#Show first 7 rows
data.head(7)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa

In [104]:
#Show last 5 rows
data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

<a id="8"></a>
**3. REGULATING DATA**

In [105]:
#If numbers are defined as a string, we can change them to numeric
data.SepalLengthCm = pd.to_numeric(data.SepalLengthCm, errors='coerce')

In [106]:
##If there is a null its values returns True
data.isnull().head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0  False          False         False          False         False    False
1  False          False         False          False         False    False
2  False          False         False          False         False    False
3  False          False         False          False         False    False
4  False          False         False          False         False    False

In [107]:
#If there is a null its values returns False
data.notnull().head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0  True           True          True           True          True     True
1  True           True          True           True          True     True
2  True           True          True           True          True     True
3  True           True          True           True          True     True
4  True           True          True           True          True     True

In [108]:
#It shows is there any nan values in the columns
data.notnull().all()

Id               True
SepalLengthCm    True
SepalWidthCm     True
PetalLengthCm    True
PetalWidthCm     True
Species          True
dtype: bool

In [109]:
#It drops nan values
data.SepalLengthCm.dropna(inplace = True) 

In [110]:
#It fills nan values with 0
data.SepalLengthCm.fillna(0, inplace = True)

<a id="9"></a>
**4.INDEXING & SLICING**

In [111]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [115]:
#Get a column as a series
data["SepalLengthCm"].head()

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: SepalLengthCm, dtype: float64

In [116]:
#Get a column as a dataframe
data[["SepalLengthCm"]].head()

SepalLengthCm
0            5.1
1            4.9
2            4.7
3            4.6
4            5.0

In [117]:
#Get columns
data[["SepalLengthCm", "PetalLengthCm"]].head()

SepalLengthCm  PetalLengthCm
0            5.1            1.4
1            4.9            1.4
2            4.7            1.3
3            4.6            1.5
4            5.0            1.4

In [118]:
#Set id column as a index.
data = data.set_index('Id')
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [119]:
#Change labels index and columns
data.index.names = ['index']
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
index                                                                       
1                5.1           3.5            1.4           0.2  Iris-setosa
2                4.9           3.0            1.4           0.2  Iris-setosa
3                4.7           3.2            1.3           0.2  Iris-setosa
4                4.6           3.1            1.5           0.2  Iris-setosa
5                5.0           3.6            1.4           0.2  Iris-setosa

In [120]:
#Add one more index
data.set_index('Species', append=True).head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
index Species                                                              
1     Iris-setosa            5.1           3.5            1.4           0.2
2     Iris-setosa            4.9           3.0            1.4           0.2
3     Iris-setosa            4.7           3.2            1.3           0.2
4     Iris-setosa            4.6           3.1            1.5           0.2
5     Iris-setosa            5.0           3.6            1.4           0.2

In [121]:
#Change the index values
#data.index = range(100,len(data.index)+100)
#data.head()

In [122]:
#Changing column names
data = data.rename(columns={'SepalLengthCm':'SLCM','SepalWidthCm':'SWCM', 'PetalLengthCm':'PLCM', 'PetalWidthCm': 'PWCM'})
data.columns

Index(['SLCM', 'SWCM', 'PLCM', 'PWCM', 'Species'], dtype='object')

In [124]:
#Indexing and Slicing
data.loc[2:4, ["PLCM"]]

PLCM
index      
2       1.4
3       1.3
4       1.5

In [127]:
data.loc[2:4, "PLCM":]

PLCM  PWCM      Species
index                         
2       1.4   0.2  Iris-setosa
3       1.3   0.2  Iris-setosa
4       1.5   0.2  Iris-setosa

In [126]:
data.loc[1:5,"PLCM": ]

PLCM  PWCM      Species
index                         
1       1.4   0.2  Iris-setosa
2       1.4   0.2  Iris-setosa
3       1.3   0.2  Iris-setosa
4       1.5   0.2  Iris-setosa
5       1.4   0.2  Iris-setosa

In [128]:
data.loc[1:3 , ["PLCM", "Species"]]

PLCM      Species
index                   
1       1.4  Iris-setosa
2       1.4  Iris-setosa
3       1.3  Iris-setosa

<a id="10"></a>
**5.FILTERING & TRANSFORMING**

In [129]:
data.head()

SLCM  SWCM  PLCM  PWCM      Species
index                                     
1       5.1   3.5   1.4   0.2  Iris-setosa
2       4.9   3.0   1.4   0.2  Iris-setosa
3       4.7   3.2   1.3   0.2  Iris-setosa
4       4.6   3.1   1.5   0.2  Iris-setosa
5       5.0   3.6   1.4   0.2  Iris-setosa

In [130]:
#Applying lambda function SLCM column
data.SLCM = data.SLCM.apply(lambda n : n/2)
data.head()

SLCM  SWCM  PLCM  PWCM      Species
index                                     
1      2.55   3.5   1.4   0.2  Iris-setosa
2      2.45   3.0   1.4   0.2  Iris-setosa
3      2.35   3.2   1.3   0.2  Iris-setosa
4      2.30   3.1   1.5   0.2  Iris-setosa
5      2.50   3.6   1.4   0.2  Iris-setosa

In [131]:
# Defining column using other columns
data["total_lengthCM"] = data.SLCM + data.PLCM
data.head(3)

SLCM  SWCM  PLCM  PWCM      Species  total_lengthCM
index                                                     
1      2.55   3.5   1.4   0.2  Iris-setosa            3.95
2      2.45   3.0   1.4   0.2  Iris-setosa            3.85
3      2.35   3.2   1.3   0.2  Iris-setosa            3.65

In [132]:
# Creating boolean series
boolean = data.SLCM > 3.5
data[boolean]

SLCM  SWCM  PLCM  PWCM         Species  total_lengthCM
index                                                        
103    3.55   3.0   5.9   2.1  Iris-virginica            9.45
106    3.80   3.0   6.6   2.1  Iris-virginica           10.40
108    3.65   2.9   6.3   1.8  Iris-virginica            9.95
110    3.60   3.6   6.1   2.5  Iris-virginica            9.70
118    3.85   3.8   6.7   2.2  Iris-virginica           10.55
119    3.85   2.6   6.9   2.3  Iris-virginica           10.75
123    3.85   2.8   6.7   2.0  Iris-virginica           10.55
126    3.60   3.2   6.0   1.8  Iris-virginica            9.60
130    3.60   3.0   5.8   1.6  Iris-virginica            9.40
131    3.70   2.8   6.1   1.9  Iris-virginica            9.80
132    3.95   3.8   6.4   2.0  Iris-virginica           10.35
136    3.85   3.0   6.1   2.3  Iris-virginica            9.95

In [134]:
#Apply two filters
filter1 = data.SLCM > 3.5
filter2 = data.PLCM > 6.5
data[filter1 & filter2]

SLCM  SWCM  PLCM  PWCM         Species  total_lengthCM
index                                                        
106    3.80   3.0   6.6   2.1  Iris-virginica           10.40
118    3.85   3.8   6.7   2.2  Iris-virginica           10.55
119    3.85   2.6   6.9   2.3  Iris-virginica           10.75
123    3.85   2.8   6.7   2.0  Iris-virginica           10.55

<a id="11"></a>
**6.DATA ANALYSIS**

    -count: number of entries
    -mean: average of entries
    -std: standart deviation
    -min: minimum entry
    -25%: first quantile (Q1)
    -50%: median or second quantile
    -75%: third quantile (Q3)
    -max: maximum entry
    
    And IQR = (Q3-Q1)
    If there is a data smaller than Q1 - 1.5(IQR) or bigger than Q3 + 1.5(IQR), we can drop them. Those datas are irrelevant.

In [135]:
data.describe()

SLCM        SWCM        PLCM        PWCM  total_lengthCM
count  150.000000  150.000000  150.000000  150.000000      150.000000
mean     2.921667    3.054000    3.758667    1.198667        6.680333
std      0.414033    0.433594    1.764420    0.763161        2.135014
min      2.150000    2.000000    1.000000    0.100000        3.250000
25%      2.550000    2.800000    1.600000    0.300000        4.112500
50%      2.900000    3.000000    4.350000    1.300000        7.175000
75%      3.200000    3.300000    5.100000    1.800000        8.325000
max      3.950000    4.400000    6.900000    2.500000       10.750000

<a id="12"></a>
**7. CONCATENATING**

In [136]:
#CONCAT ROWS
data1 = data.head()
data2= data.tail()
rows_concat = pd.concat([data1,data2])
rows_concat

SLCM  SWCM  PLCM  PWCM         Species  total_lengthCM
index                                                        
1      2.55   3.5   1.4   0.2     Iris-setosa            3.95
2      2.45   3.0   1.4   0.2     Iris-setosa            3.85
3      2.35   3.2   1.3   0.2     Iris-setosa            3.65
4      2.30   3.1   1.5   0.2     Iris-setosa            3.80
5      2.50   3.6   1.4   0.2     Iris-setosa            3.90
146    3.35   3.0   5.2   2.3  Iris-virginica            8.55
147    3.15   2.5   5.0   1.9  Iris-virginica            8.15
148    3.25   3.0   5.2   2.0  Iris-virginica            8.45
149    3.10   3.4   5.4   2.3  Iris-virginica            8.50
150    2.95   3.0   5.1   1.8  Iris-virginica            8.05

In [138]:
#CONCAT COLUMNS
data1 = data['SLCM'].head()
data2= data['PLCM'].head()
cols_concat = pd.concat([data1,data2], axis=1) 
cols_concat

SLCM  PLCM
index            
1      2.55   1.4
2      2.45   1.4
3      2.35   1.3
4      2.30   1.5
5      2.50   1.4

<a id="13"></a>
**8. PIVOTING**

In [139]:
dic = {"treatment":["A","B","B","A"],"gender":["F","M","F","M"],"response":[10,45,5,9],"age":[15,4,72,65]}
df = pd.DataFrame(dic)
df

treatment gender  response  age
0         A      F        10   15
1         B      M        45    4
2         B      F         5   72
3         A      M         9   65

In [140]:
#PIVOTING
df.pivot(index="gender", columns="treatment", values=["response", "age"])

response     age    
treatment        A   B   A   B
gender                        
F               10   5  15  72
M                9  45  65   4

<a id="14"></a>
**9.MELTING**

Reverse of pivoting

In [141]:
df

treatment gender  response  age
0         A      F        10   15
1         B      M        45    4
2         B      F         5   72
3         A      M         9   65

In [142]:
pd.melt(df, id_vars="treatment", value_vars=["gender","age"])

treatment variable value
0         A   gender     F
1         B   gender     M
2         B   gender     F
3         A   gender     M
4         A      age    15
5         B      age     4
6         B      age    72
7         A      age    65

<a id="15"></a>
**10. STACKING AND UNSTACKING**

It reshapes dataframes.

In [143]:
df

treatment gender  response  age
0         A      F        10   15
1         B      M        45    4
2         B      F         5   72
3         A      M         9   65

In [144]:
df1 = df.set_index(["treatment","gender"])
df1

response  age
treatment gender               
A         F             10   15
B         M             45    4
          F              5   72
A         M              9   65

In [145]:
#UNSTACKING
# level determines indexes
df1.unstack(level=1)

response     age    
gender           F   M   F   M
treatment                     
A               10   9  15  65
B                5  45  72   4

In [146]:
df1.unstack(level=0)

response     age    
treatment        A   B   A   B
gender                        
F               10   5  15  72
M                9  45  65   4

In [147]:
# change inner and outer level index position
df2 = df1.swaplevel(0,1)
df2

response  age
gender treatment               
F      A                10   15
M      B                45    4
F      B                 5   72
M      A                 9   65

<a id="16"></a>
**11.GROUPBY**

In [148]:
data.head()

SLCM  SWCM  PLCM  PWCM      Species  total_lengthCM
index                                                     
1      2.55   3.5   1.4   0.2  Iris-setosa            3.95
2      2.45   3.0   1.4   0.2  Iris-setosa            3.85
3      2.35   3.2   1.3   0.2  Iris-setosa            3.65
4      2.30   3.1   1.5   0.2  Iris-setosa            3.80
5      2.50   3.6   1.4   0.2  Iris-setosa            3.90

In [149]:
#Group by according to Species and calculate the mean
data.groupby('Species').mean()

SLCM   SWCM   PLCM   PWCM  total_lengthCM
Species                                                    
Iris-setosa      2.503  3.418  1.464  0.244           3.967
Iris-versicolor  2.968  2.770  4.260  1.326           7.228
Iris-virginica   3.294  2.974  5.552  2.026           8.846

In [150]:
#Groupby and sum
data.groupby('Species').sum()

SLCM   SWCM   PLCM   PWCM  total_lengthCM
Species                                                     
Iris-setosa      125.15  170.9   73.2   12.2          198.35
Iris-versicolor  148.40  138.5  213.0   66.3          361.40
Iris-virginica   164.70  148.7  277.6  101.3          442.30

In [151]:
#print setosa's summed values
data.groupby('Species').sum().loc["Iris-setosa"] #It returns series

SLCM              125.15
SWCM              170.90
PLCM               73.20
PWCM               12.20
total_lengthCM    198.35
Name: Iris-setosa, dtype: float64

In [152]:
data.groupby('Species').sum().loc[["Iris-setosa"]] #It returns dataframe

SLCM   SWCM  PLCM  PWCM  total_lengthCM
Species                                               
Iris-setosa  125.15  170.9  73.2  12.2          198.35

In [154]:
#print max SWCM, PLCM,PWCM values of versicolor
data.groupby('Species').max().loc[["Iris-versicolor"], "SWCM":"PWCM"]

SWCM  PLCM  PWCM
Species                          
Iris-versicolor   3.4   5.1   1.8

In [155]:
#print PLCM,PWCM and total_lengthCM values of 1 and 2 rows
data.groupby('Species').max().iloc[[1,2] , -3:]

PLCM  PWCM  total_lengthCM
Species                                    
Iris-versicolor   5.1   1.8            8.35
Iris-virginica    6.9   2.5           10.75

In [159]:
df

treatment gender  response  age
0         A      F        10   15
1         B      M        45    4
2         B      F         5   72
3         A      M         9   65

In [160]:
df.groupby("treatment")[["response", "age"]].min()

response  age
treatment               
A                 9   15
B                 5    4

In [161]:
df.groupby(["treatment", "gender"]).mean()

response  age
treatment gender               
A         F             10   15
          M              9   65
B         F              5   72
          M             45    4

<a id="17"></a>
**11.MERGE**

In [162]:
dic1= { "Name":["alice","bob","clarke", "steve","eva", "jason"],
        "Ages":[25,36,40,44,33,28],
        "Salary":[100,232, 300, 50, 140,500] }
#Creating a dataframe
dt1= pd.DataFrame(dic1)
dt1

Name  Ages  Salary
0   alice    25     100
1     bob    36     232
2  clarke    40     300
3   steve    44      50
4     eva    33     140
5   jason    28     500

In [163]:
dic2= { "Name":["eva", "clarke", "bob", "steve", "jason", "alice"],
         "Experience" : [4, 2, 5, 10, 2, 3 ] }
#Creating a dataframe
dt2= pd.DataFrame(dic2)
dt2

Name  Experience
0     eva           4
1  clarke           2
2     bob           5
3   steve          10
4   jason           2
5   alice           3

In [164]:
#Merging 2 dataframes according to names
dt = pd.merge(dt1, dt2)
dt

Name  Ages  Salary  Experience
0   alice    25     100           3
1     bob    36     232           5
2  clarke    40     300           2
3   steve    44      50          10
4     eva    33     140           4
5   jason    28     500           2

**--END--**